import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBare from "./component/NavBare";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" fixed w-full ">
          <NavBare />
        </div>
        {children}
      </body>
    </html>
  );
}
